import math
import os

def generate_lut():
    DEPTH = 1024
    WIDTH = 14
    MAX_VAL = (2**(WIDTH-1)) - 1  # 8191

    rtl_dir = "modeling/rtl"
    sv_filename = f"{rtl_dir}/sine_lut.sv"
    mem_filename = f"{rtl_dir}/sine_lut.mem"

    # Check directory
    os.makedirs(rtl_dir, exist_ok=True)

    # Generate .mem file (hex format for $readmemh)
    with open(mem_filename, "w") as f:
        for idx in range(DEPTH):
            sine_val = math.sin(2 * math.pi * idx / DEPTH)
            val = int(round(sine_val * MAX_VAL))
            # Convert to unsigned 14-bit hex (2's complement for negative values)
            if val < 0:
                val = (1 << WIDTH) + val
            f.write(f"{val:04X}\n")
    
    print(f"Generated {mem_filename}")

    # Generate .sv file with $readmemh initialization
    with open(sv_filename, "w") as f:
        f.write("// Optimized Sine LUT using Block RAM\n")
        f.write("// Auto-generated by modeling/gen_lut.py\n")
        f.write("// Initialized from sine_lut.mem using $readmemh for reliable FPGA synthesis\n\n")
        f.write("module sine_lut (\n")
        f.write("    input  wire clk,\n")
        f.write(f"    input  wire [{int(math.log2(DEPTH))-1}:0] addr,\n")
        f.write(f"    output reg signed [{WIDTH-1}:0] data\n")
        f.write(");\n\n")

        f.write("    // Force Block RAM usage to save LUT resources\n")
        f.write("    (* rom_style = \"block\" *)\n")
        f.write(f"    reg [{WIDTH-1}:0] sine_rom [0:{DEPTH-1}];\n\n")

        f.write("    // Initialize ROM from external file - most reliable method for Vivado\n")
        f.write("    initial begin\n")
        f.write('        $readmemh("sine_lut.mem", sine_rom);\n')
        f.write("    end\n\n")

        f.write("    // Block RAM read (1 cycle latency)\n")
        f.write("    always_ff @(posedge clk) begin\n")
        f.write("        data <= $signed(sine_rom[addr]);\n")
        f.write("    end\n\n")

        f.write("endmodule\n")

    print(f"Generated {sv_filename}")

if __name__ == "__main__":
    generate_lut()
