// Optimized Sine LUT using Block RAM
// Auto-generated by modeling/gen_lut.py
// Initialized from sine_lut.mem using $readmemh for reliable FPGA synthesis

module sine_lut (
    input  wire clk,
    input  wire [9:0] addr,
    output reg signed [13:0] data
);

    // Force Block RAM usage to save LUT resources
    (* rom_style = "block" *)
    reg [13:0] sine_rom [0:1023];

    // Initialize ROM from external file - this is the most reliable method for Vivado
    initial begin
        $readmemh("sine_lut.mem", sine_rom);
    end

    // Block RAM read (1 cycle latency)
    always_ff @(posedge clk) begin
        data <= $signed(sine_rom[addr]);
    end

endmodule
